# Generated by Django 4.2 on 2023-05-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericRules',
            new_name='GenericRule',
        ),
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
